language: php

php:
    - 5.5
    - 5.4
    - 5.3

env:
    - SYMFONY_VERSION=2.0.*
    - SYMFONY_VERSION=2.1.*
    - SYMFONY_VERSION=2.2.*
    - SYMFONY_VERSION=dev-master

before_script: composer install --dev

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
    - php vendor/bin/coveralls
